### ISSUE TITLE
PHP Configuration pull

### ISSUE THREAD

**Issue by AchillesD9** [rconfig/rConfig-templates#1]
I get the following output when pulling a configuration file on Rconfig however I can SSH to the device and credentials use in Rconfig work

2018-02-19  09:58:21 CONN Success: Show Command 'term length 0 ' for device  'Switch' successful (File:  /lib/ajaxHandlers/ajaxDownloadNow.php)
--
2018-02-19 09:58:21  CONN Failure: Unable to connect via SSH to Switch -  x.x.x.x for command (term length 0 )  when running Router ID 14 - in   Error:(File: /lib/ajaxHandlers/ajaxDownloadNow.php)
2018-02-19 09:58:21  CONN Error: Authentication Failed or unable to connect to x.x.x.x on  port 22 - (File: /lib/ajaxHandlers/ajaxDownloadNow.php)

Any ideas on how to get this resolved?

**Comment by rconfig** [comment]
Hi,
 
Your issue is likely to be either;
A file permission issue, run ‘chown -R apache /home/rconfig‘ on the CLI
A credential issue - your error clearly says "Authentication Failed"
A prompt configuration issue (has the correct device prompt been placed on the device config page in rConfig)
Or other connectivity issue. KB2001 on the knowledge base @rconfig.com can help assist you.
Please read help files and support documentation.
 
I do not provide direct support unless you pay for support. Sorry, but otherwise I could not eat 😊
 
Regards

**Comment by AchillesD9** [comment]
I've went through the steps provided ran the interactive manual interactive script and I'm only receiving the following error:

Failure: Unable to connect to Switch - x.x.x.x when running taskID 176702 - in  Error:(File: /home/rconfig/lib/showCmdScript.php)

**Comment by AchillesD9** [comment]
Managed to come right eventually, I setup the username with defaults which it was not sending through when running the schedule however the issue I am now facing is within the code

Success: Connected to Switch (x.x.x.x) for taskID 176702 - in (File: /home/rconfig/lib/showCmdScript.php)
19 February 2018 12:38:42 PM
show running-config 19 February 2018 12:38:52 PM
PHP Warning:  implode(): Invalid arguments passed in /home/rconfig/lib/showCmdScript.php on line 240

Warning: implode(): Invalid arguments passed in /home/rconfig/lib/showCmdScript.php on line 240
19 February 2018 12:38:52 PM
term length 0 19 February 2018 12:39:02 PM
PHP Warning:  implode(): Invalid arguments passed in /home/rconfig/lib/showCmdScript.php on line 240

Warning: implode(): Invalid arguments passed in /home/rconfig/lib/showCmdScript.php on line 240
PHP Notice:  Undefined index: exitCmd in /home/rconfig/lib/showCmdScript.php on line 265

Notice: Undefined index: exitCmd in /home/rconfig/lib/showCmdScript.php on line 265

If anyone has seen this issue before, some help would be appreciated.

**Comment by AchillesD9** [comment]
Managed to fix the issue on line 265. The exit cmd line wasn't lined up correctly in the rconfig script.

Trying to fix line 240 at the moment.

**Comment by AchillesD9** [comment]
Managed to fix the issue, the array was being created twice.

**Comment by rconfig** [comment]
Undefined index: exitCmd means the exitCmd was missing fromt he template file. Thats not a bug, its a misconfiguration of the template i'd say.

Not sure what you mean by the 'array was being created twice'
