### ISSUE TITLE
How to backup multiple vdom

### ISSUE THREAD

**Issue by panhala** [rconfig/rConfig-templates#10]
Hi support,

My Fortigate has multiple vdom. Can you tell me how to backup it?

**Comment by rConfigRich** [comment]
Hello Panhala, my name is Rich with rConfig. Can you please direct your question directly to our support email (help@rconfig.com). From there we can work to see if this is something we can assist you with sorting out. Thank you.

**Comment by stephenstack** [comment]
All issues with rConfig templates must be logged via enterprise support ticket.
