### ISSUE TITLE
Aruba Switches Template

### ISSUE THREAD

**Issue by jomupra** [rconfig/rConfig-templates#11]
Hi guys

I have a problem. When create a manual backup with "hp-procurve-ssh-noenable.yml" and command show running-config appear this line when enter space to continue

**[24;1H[2K[24;1H[1;24r[24;1H**   untagged 12-47

   tagged 48

   no ip address

   exit

Switch model is  Aruba 2930F (JL260A) with firmware WC.16.06.0006

Could you help me??

**Comment by a1ad** [comment]
Same here, why is this issue closed with no solution?
