### ISSUE TITLE
HP J9772A 2530-48G

### ISSUE THREAD

**Issue by max-rh** [rconfig/rConfig-templates#12]
Hello, 

I am trying to backup a HP J9772A 2530-48G switch with no luck; I did try using the cisco and the hp procurve templates with no luck with " show running-config" command.

Any advice ?

Thanks

**Comment by AchillesD9** [comment]
I managed to add a workaround - I amended the command "show running-config" to "show running-config | b hostname" - mainly for the fact that Rconfig by default didn't play well with "!" in the configuration file when it starts. That fixed it for me.
