### ISSUE TITLE
fortinet template for SSH not working

### ISSUE THREAD

**Issue by eman-abdelghani** [rconfig/rConfig-templates#16]
I added cisco devices to rConfig successfully,   I download fortinet template from github and added to rConfig system, but when added the fortinet devices and try to download the configuration I got empty file and the below log:
2018-12-25 12:06:00 CONN Failure: Unable to connect via SSH to Firewall - x.x.x.x for command (show)  when running Router ID 25 - in  Error:(File: /lib/ajaxHandlers/ajaxDownloadNow.php)

2018-12-25 12:06:00 CONN Error: Authentication Failed or unable to connect to x.x.x.x on port 22 - (File: /lib/ajaxHandlers/ajaxDownloadNow.php)
I am sure that the credential is correct. what causes of this problem?

**Comment by wouterschoonees** [comment]
I have the same issue: CONN Error: Authentication Failed for 1.1.1.1 (File: /lib/ajaxHandlers/ajaxConfigDevice.php)

In the router log it seems to be a SSH version mismatch or weak ciphers:
SSHD_[65817]: %SECURITY-SSHD-6-INFO_GENERAL : Client 1.1.1.2 closes socket connection 
SSHD_[65817]: %SECURITY-SSHD-3-ERR_GENERAL : Failed in version exchange 
SSHD_[65817]: %SECURITY-SSHD-6-INFO_GENERAL : Client 1.1.1.2 closes socket connection 
SSHD_[65817]: %SECURITY-SSHD-3-ERR_GENERAL : Failed in version exchange 
SSHD_[1156]: %SECURITY-SSHD-6-INFO_GENERAL : Incoming SSH session rate limit exceeded 
SSHD_[65817]: %SECURITY-SSHD-6-INFO_GENERAL : Client 1.1.1.2 closes socket connection 
SSHD_[65817]: %SECURITY-SSHD-3-ERR_GENERAL : Failed in version exchange

**Comment by amaurybsouza** [comment]
I'm working in templates of the rConfig, and I'd link to know if anybody have the template for devices Extreme.

Thanks.

**Comment by martinparr** [comment]
> 
> 
> I added cisco devices to rConfig successfully, I download fortinet template from github and added to rConfig system, but when added the fortinet devices and try to download the configuration I got empty file and the below log:
> 2018-12-25 12:06:00 CONN Failure: Unable to connect via SSH to Firewall - x.x.x.x for command (show) when running Router ID 25 - in Error:(File: /lib/ajaxHandlers/ajaxDownloadNow.php)
> 
> 2018-12-25 12:06:00 CONN Error: Authentication Failed or unable to connect to x.x.x.x on port 22 - (File: /lib/ajaxHandlers/ajaxDownloadNow.php)
> I am sure that the credential is correct. what causes of this problem?

can you ssh from the rConfig host directly to the Fortigate in question?

**Comment by rconfig** [comment]
All issues with rConfig templates must be logged via enterprise support ticket.
