### ISSUE TITLE
how to delete configured device or old configuration backup permenantly from fortigate

### ISSUE THREAD

**Issue by eman-abdelghani** [rconfig/rConfig-templates#17]

**Comment by amaurybsouza** [comment]
hey @eman-abdelghani do you solved the problem with template fortigate?

Thanks.

**Comment by eman-abdelghani** [comment]
No. Actually the template shared here for fortinet devices works in some fortinet devices, but still there is fortigate cluster didnot work and i do not found where is the problem.

**Comment by rconfig** [comment]
All issues with rConfig templates must be logged via enterprise support ticket.
