### ISSUE TITLE
Dell PowerConnect 5524 ssh two login prompts

### ISSUE THREAD

**Issue by mr-at** [rconfig/rConfig-templates#18]
Does anyone know how to make a template for a SSH connection to Dell PowerConnect 5524 switches? The first prompt is "login as:" and after that you get "User Name:" Doesn't matter what you enter after "Login as:", but it needs at least an extra confirmation.

**Comment by rconfig** [comment]
All issues with rConfig templates must be logged via enterprise support ticket.
