### ISSUE TITLE
HP Procurve template

### ISSUE THREAD

**Issue by glenp42** [rconfig/rConfig-templates#2]
Just wondering if anyone has used this template successfully...

The procurves respond with terminal codes back to any 'show running-config' command and this seems to be upsetting rconfig and results in a partial file saved even with pagination is turned off with 'no page'.
hpAnyKeyStatus : on does not seem to work correctly and results in it not getting past the MOTD
hpAnyKeyStatus : off is the only way I can get a response from the procurve.

In my case I am testing against a Procurve3800 stack running KA.16.04.0008...

resultant file from 'show running-config'
------
[?25h[24;1H[?25h[24;1H

Running configuration:

**Comment by AchillesD9** [comment]
I have the exact same issue when backing up a HP switch in our network. It doesn't page and I'm getting the exact same result.

**Comment by AchillesD9** [comment]
I use a workaround to get this working for me, in the commands sections on Rconfig, instead of using the command "show running-config", I used "show running-config | b hostname" - it will include all the configuration after that point. I am now able to pull the configuration.

**Comment by rizkhat** [comment]
This works like a charm!! Thank You.

**Comment by AchillesD9** [comment]
Awesome! Glad my solution helped you :)

**Comment by rconfig** [comment]
thanks

**Comment by marsfn** [comment]
Unfortunately, this command also it's not getting full config it's like half of config showing :( My Sw HP-3500yl.
