### ISSUE TITLE
Fresh install scheduler.php broken

### ISSUE THREAD

**Issue by adam1942** [rconfig/rConfig-templates#20]
Just completed a fresh install. I can create schedules however they do not work. Checking crontab against the users on the system no cron jobs are created.

Logs show the following message when I browse to "Scheduled Tasks" even if I create no logs;

2019-02-18 13:23:34 WARN Failure: Problem Displaying snippetsOptions() options (File: /scheduler.php)
2019-02-18 13:23:34 WARN Failure: Problem Displaying complianceReports options (File: /scheduler.php)

Version 3.9.2 on CentOS 7 minimal. User account is the built-in account named "admin"

**Comment by Aacis01** [comment]
same issue with me. did the issue resolve in your case?

**Comment by adam1942** [comment]
The latest version resolved this issue :)
