### ISSUE TITLE
show running-config output cut off

### ISSUE THREAD

**Issue by rizzodieratte** [rconfig/rConfig-templates#23]
Hi all,
when i run the show running-config backup command the config file cut off after a few lines.
Mostly this is after "crypto pki certificate chain TP-self-signed-1231460864".
I tried both the telnet and ssh template, but without success.
Is there a way to fix this?

**Comment by jchrisloyd** [comment]
I have the same issue, were you able to find a fix? Thanks

**Comment by rizzodieratte** [comment]
Yes, i do not know why this is a problem, but i changed the "show running-config" command to the short version "show run" and its working without problems since month.
You can change this under Devices --> Commands for all devices in the category.
It would be nice if you let me know this fixed the problem for you too.

**Comment by jchrisloyd** [comment]
rizzodieratte, Thank you for your suggestion, I tried this and unfortunately it did not help. This only seems to happen on some devices, and not others.

**Comment by myintmo-geeks** [comment]
Hello everyone. Is it solve ? Cause i also don't know how to do .

**Comment by adehmily** [comment]
I have the same issue, pls help

**Comment by willcurtis** [comment]
Check your device config to see what the main prompt is set as, I had set mine originally as just # but after changing to the actual hostname of the device it stopped cutting the configs short

**Comment by radiognomeinvisible** [comment]
> Check your device config to see what the main prompt is set as, I had set mine originally as just # but after changing to the actual hostname of the device it stopped cutting the configs short

Thank you for your advice. Changing the main prompt to the actual hostname actually solved config cutoff problem (at least on 2 different devices - H3C L3 and Cisco L2 switches).

**Comment by sepp016** [comment]
Hello,
problem with cut off configs etc is in most cases a paging/scrolling problem. There is a easy to verfiy and fix this. Connect to your switch with the same settings configured for this switch in rconfig (ssh, telnet etc). Type your command, like show running-config and press enter once. Compare the last line of the output on your screen with the one from rconfig. If the match, there is a  paging/scrolling problem in your connection template. This means rconfig does not recognise the pagerPromt and cannot scroll down to the end of config.
These three settings are located in your Connection Template under config:

-    # Disable config scrolling/ paging command. Leave blank, or set as required. Must place command in quotations
    pagingCmd: 
    # re-enable config scrolling/ paging command. Leave blank, or set as required. Must place command in quotations
    resetPagingCmd:
    # Set pager prompt. Must place command in quotations
    pagerPrompt: 

**For Cisco enterprise Switches a easy fix is:**

pagingCmd:  "terminal no length"
resetPagingCmd: "terminal lines 28" <--28 lines as an example



**As an exemaple, here a template to get cisco SMB (SG300 etc) switches working:**

# rConfig connection template - DO NOT EDIT DIRECTLY
## Notes: 
    ## Remember to update permissions for the templates folder after uploading new template files.
    ## run 'chown -R apache /home/rconfig' on your rconfig server CLI
    ## all items below that contain free text should be contained within quotation marks " "
    ## For new community submitted templates visit: https://github.com/rconfig/rConfig-templates

main:
  name: "Cisco IOS SMB - SSH - No Enable"
  desc: "Cisco IOS SSH based connection without enable mode"
connect:
  # connection timeout in seconds
  timeout: 60
  # type either telnet or ssh - must be in lowercase
  protocol: ssh
  # type port number for connection protocol choose from 1 - 65535
  port: 22
auth:
  # Set username name prompt. Must be in quotes. If left blank, username will not be sent.
  username: "login as:"
  # Set password name prompt. Must be in quotes
  password: ""
  # Set enable mode on or off
  enable: off
  # set enable mode command. Must be in quotes
  enableCmd: "enable"
  # set enable mode password prompt. Must be in quotes
  enablePassPrmpt: "Password:"
  # set HP 'press any key' status. Is 'on' or 'off'
  hpAnyKeyStatus: off
  # set HP 'press any key' prompt. 
  hpAnyKeyPrmpt: "Press any key to continue"  
config:
    # Experimental: Some vendors use different linebreak settings. Choose 'n' (default) or 'r'
    linebreak: "n"
    # Disable config scrolling/ paging command. on/off
    paging: on
    # Disable config scrolling/ paging command. Leave blank, or set as required. Must place command in quotations
    pagingCmd: "terminal datadump"
    # re-enable config scrolling/ paging command. Leave blank, or set as required. Must place command in quotations
    resetPagingCmd: "terminal no datadump"
    # Set pager prompt. Must place command in quotations
    pagerPrompt: "More: <space>,  Quit: q or CTRL+Z, One line: <return>"
    # Set pager prompt key-stroke. Must place command in quotations
    pagerPromptCmd: " "
    # Save configuration command. Leave blank, or set as required. Must be in quotes
    saveConfig: "wr mem"
    # Set exit command. Must place command in quotations
    exitCmd: "quit"


ben

**Comment by its-hamid** [comment]
Hi, I don't know if this still an active thread. Anyways In my environment, I have Cisco 4500 series switch, and when I run "Manual Download" in device management. It downloads approx 1700 lines of running and start-up configurations, although this switch has more than 3000 lines in its running and startup configurations. I tried by selecting "Cisco IOS SSH based connection with enable mode" in device management.

Any suggestion/idea ?

**Comment by its-hamid** [comment]
is it a limitation in rconfig or are there any workarounds available?

regards,

**Comment by Virg1984** [comment]
> ause of formatting proble

I got the same issue. if I do ssh my first page ends on the same line where Rconfig is saving.
how can I increase the line numbers? 
I am using SG 300 and tried all the templates.

**Comment by sepp016** [comment]
Have you seen my post? For Cisco SMB Switches you have to edit/create a template like this. Important are the values at resetPagingCmd and pagingCmd

# rConfig connection template - DO NOT EDIT DIRECTLY
## Notes: 
    ## Remember to update permissions for the templates folder after uploading new template files.
    ## run 'chown -R apache /home/rconfig' on your rconfig server CLI
    ## all items below that contain free text should be contained within quotation marks " "
    ## For new community submitted templates visit: https://github.com/rconfig/rConfig-templates

main:
  name: "Cisco IOS SMB - TELNET - No Enable"
  desc: "Cisco IOS TELNET based connection without enable mode"
connect:
  # connection timeout in seconds
  timeout: 30
  # type either telnet or ssh - must be in lowercase
  protocol: telnet
  # type port number for connection protocol choose from 1 - 65535
  port: 23
auth:
  # Set username name prompt. Must be in quotes. If left blank, username will not be sent.
  username: "User Name:"
  # Set password name prompt. Must be in quotes
  password: "Password"
  # Set enable mode on or off
  enable: off
  # set enable mode command. Must be in quotes
  enableCmd: "enable"
  # set enable mode password prompt. Must be in quotes
  enablePassPrmpt: "Password:"
  # set HP 'press any key' status. Is 'on' or 'off'
  hpAnyKeyStatus: off
  # set HP 'press any key' prompt. 
  hpAnyKeyPrmpt: "Press any key to continue"  
config:
    # Experimental: Some vendors use different linebreak settings. Choose 'n' (default) or 'r'
    linebreak: "n"
    # Disable config scrolling/ paging command. on/off
    paging: on
    # Disable config scrolling/ paging command. Leave blank, or set as required. Must place command in quotations
    pagingCmd: "terminal length 0"
    # re-enable config scrolling/ paging command. Leave blank, or set as required. Must place command in quotations
    resetPagingCmd: "terminal length 40"
    # Set pager prompt. Must place command in quotations
    pagerPrompt: "--More--"
    # Set pager prompt key-stroke. Must place command in quotations
    pagerPromptCmd: " "
    # Save configuration command. Leave blank, or set as required. Must be in quotes
    saveConfig: "wr mem"
    # Set exit command. Must place command in quotations
    exitCmd: "quit"

**Comment by jiritomanek85** [comment]
Hi it

> Have you seen my post? For Cisco SMB Switches you have to edit/create a template like this. Important are the values at resetPagingCmd and pagingCmd
> 
> ```
> # rConfig connection template - DO NOT EDIT DIRECTLY
> ## Notes: 
>     ## Remember to update permissions for the templates folder after uploading new template files.
>     ## run 'chown -R apache /home/rconfig' on your rconfig server CLI
>     ## all items below that contain free text should be contained within quotation marks " "
>     ## For new community submitted templates visit: https://github.com/rconfig/rConfig-templates
> 
> main:
>   name: "Cisco IOS SMB - TELNET - No Enable"
>   desc: "Cisco IOS TELNET based connection without enable mode"
> connect:
>   # connection timeout in seconds
>   timeout: 30
>   # type either telnet or ssh - must be in lowercase
>   protocol: telnet
>   # type port number for connection protocol choose from 1 - 65535
>   port: 23
> auth:
>   # Set username name prompt. Must be in quotes. If left blank, username will not be sent.
>   username: "User Name:"
>   # Set password name prompt. Must be in quotes
>   password: "Password"
>   # Set enable mode on or off
>   enable: off
>   # set enable mode command. Must be in quotes
>   enableCmd: "enable"
>   # set enable mode password prompt. Must be in quotes
>   enablePassPrmpt: "Password:"
>   # set HP 'press any key' status. Is 'on' or 'off'
>   hpAnyKeyStatus: off
>   # set HP 'press any key' prompt. 
>   hpAnyKeyPrmpt: "Press any key to continue"  
> config:
>     # Experimental: Some vendors use different linebreak settings. Choose 'n' (default) or 'r'
>     linebreak: "n"
>     # Disable config scrolling/ paging command. on/off
>     paging: on
>     # Disable config scrolling/ paging command. Leave blank, or set as required. Must place command in quotations
>     pagingCmd: "terminal length 0"
>     # re-enable config scrolling/ paging command. Leave blank, or set as required. Must place command in quotations
>     resetPagingCmd: "terminal length 40"
>     # Set pager prompt. Must place command in quotations
>     pagerPrompt: "--More--"
>     # Set pager prompt key-stroke. Must place command in quotations
>     pagerPromptCmd: " "
>     # Save configuration command. Leave blank, or set as required. Must be in quotes
>     saveConfig: "wr mem"
>     # Set exit command. Must place command in quotations
>     exitCmd: "quit"
> ```
 Hi i tried all the template settings in rconfig. Rconfig backup only 1st page. 
Here is my settings template:

`# rConfig connection template - DO NOT EDIT DIRECTLY
## Notes: 
    ## Remember to update permissions for the templates folder after uploading new template files.
    ## run 'chown -R apache /home/rconfig' on your rconfig server CLI
    ## all items below that contain free text should be contained within quotation marks " "
    ## For new community submitted templates visit: https://github.com/rconfig/rConfig-templates

main:
  name: "Cisco SG 300"
  desc: "Cisco SG 300"
connect:
  # connection timeout in seconds
  timeout: 30
  # type either telnet or ssh - must be in lowercase
  protocol: ssh
  # type port number for connection protocol choose from 1 - 65535
  port: 22
auth:
  # Set username name prompt. Must be in quotes. If left blank, username will not be sent.
  username: "User Name:"
  # Set password name prompt. Must be in quotes
  password: "Password"
  # Set enable mode on or off
  enable: off
  # set enable mode command. Must be in quotes
  enableCmd: "enable"
  # set enable mode password prompt. Must be in quotes
  enablePassPrmpt: "Password:"
  # set HP 'press any key' status. Is 'on' or 'off'
  hpAnyKeyStatus: off
  # set HP 'press any key' prompt. 
  hpAnyKeyPrmpt: "Press any key to continue"  
config:
    # Experimental: Some vendors use different linebreak settings. Choose 'n' (default) or 'r'
    linebreak: "n"
    # Disable config scrolling/ paging command. on/off
    paging: on
    # Disable config scrolling/ paging command. Leave blank, or set as required. Must place command in quotations
    pagingCmd: ""
    # re-enable config scrolling/ paging command. Leave blank, or set as required. Must place command in quotations
    resetPagingCmd: "terminal length 24"
    # Set pager prompt. Must place command in quotations
    pagerPrompt: "More: <space>,  Quit: q or CTRL+Z, One line: <return>
"
    # Set pager prompt key-stroke. Must place command in quotations
    pagerPromptCmd: " "
    # Save configuration command. Leave blank, or set as required. Must be in quotes
    saveConfig: "wr mem"
    # Set exit command. Must place command in quotations
    exitCmd: "quit"
![RemoteDesktopManager64_Ga4p2OsfEj](https://user-images.githubusercontent.com/11149271/201067229-d8643329-8694-44ae-abe1-252cd9e39e94.png)
`

Can somebody help me? Thank you.

**Comment by jadedmia** [comment]
SG350XG here...

This is what I needed:

   # rConfig connection template - DO NOT EDIT DIRECTLY
## Notes:
## Remember to update permissions for the templates folder after uploading new template files.
## run 'chown -R apache /home/rconfig' on your rconfig server CLI
## all items below that contain free text should be contained within quotation marks " "
## For new community submitted templates visit: https://github.com/rconfig/rConfig-templates

main:
  name: 'Cisco IOS SG350XG- SSH - No Enable'
  desc: 'Cisco IOS SG350XG SSH based connection without enable mode'
connect:
  # connection timeout in seconds
  timeout: 30
  # type either telnet or ssh - must be in lowercase
  protocol: ssh
  # type port number for connection protocol choose from 1 - 65535
  port: 22
auth:
  # Set username name prompt. Must be in quotes. If left blank, username will not be sent.
  username: 'Username:'
  # Set password name prompt. Must be in quotes
  password: 'Password:'
  # Set enable mode on or off
  enable: off
  # set enable mode command. Must be in quotes
  enableCmd: 'enable'
  # set enable mode password prompt. Must be in quotes
  enablePassPrmpt: 'Password:'
  # set HP 'press any key' status. Is 'on' or 'off'
  hpAnyKeyStatus: off
  # set HP 'press any key' prompt.
  hpAnyKeyPrmpt: 'Press any key to continue'
config:
  # Experimental: Some vendors use different linebreak settings. Choose 'n' (default) or 'r'
  linebreak: 'n'
  # Disable config scrolling/ paging command. on/off
  paging: on
  # Disable config scrolling/ paging command. Leave blank, or set as required. Must place command in quotations
  pagingCmd: 'terminal datadump'
  # re-enable config scrolling/ paging command. Leave blank, or set as required. Must place command in quotations
  resetPagingCmd: ''
  # Set pager prompt. Must place command in quotations
  pagerPrompt: '--More--'
  # Set pager prompt key-stroke. Must place command in quotations
  pagerPromptCmd: "" 
  # Save configuration command. Leave blank, or set as required. Must be in quotes
  saveConfig: 'wr mem'
  # Set exit command. Must place command in quotations
  exitCmd: 'quit'


Hope it helps..

**Comment by stephenstack** [comment]
If you can submit in plain text or yml formatted, that would really help
