### ISSUE TITLE
HP 1950 - Unable to Connect

### ISSUE THREAD

**Issue by itechinfra** [rconfig/rConfig-templates#26]
Hi, i'm trying to use rConfig with my switches. Just deployed the tool but im not getting any luck setting a switch up into rConfig.

I put all my data into the device field, and receive the following message:

2019-06-03 18:25:18 CONN Failure: Unable to connect to Backbone1 - 172.18.24.51 for Router ID 2. See Connection logs for details - in Error:(File: /lib/ajaxHandlers/ajaxDownloadNow.php)
2019-06-03 18:25:18 CONN Error: Authentication Failed for enable mode for enable mode for or 172.18.24.51 (File: /lib/ajaxHandlers/ajaxDownloadNow.php)

Im trying to manually export the config just to see if it works, but it doesnt. Dunno if there is something wrong on the parameters, but im following the switch manual and such.

**Comment by parkaos** [comment]
hi, also ios to trying to connect to my switch 1950, how do you connect to the switch? ssh or telnet?

In my case for example, I only access the switch via telenet, so in the template I had to change the protocol from ssh to telenet and the communication port from 22 to 23

I can see from the log that I connect without any problem, but I have the problem in enabling xtd-cli-mode, to get the switch configuration, at the moment I am still trying to figure out how to modify the template to get around this issue.
