### ISSUE TITLE
Juinper SRX Platform

### ISSUE THREAD

**Issue by rkayutkin** [rconfig/rConfig-templates#28]
Was anyone able to get rconfig working with the SRX platform? I tried the juniper-switch.yml template but that one isn't able to work again. Wondering if anyone is successfully backing those up or not?

**Comment by Maxonet** [comment]
Hi,
I've slightly modified the original template and now it works with Juniper SRX. Please note, you have to use " | no-more". Please see the attached template, just rename it to .yml
[junos-ssh-test2.txt](https://github.com/rconfig/rConfig-templates/files/3758024/junos-ssh-test2.txt)


The backup command I use is "show | display set | no-more"

**Comment by Maxonet** [comment]
Hi @rkayutkin 

You can try this Juniper SRX connection template.
I use it with the following backup comamnds:
```
show configuration | display set | no-more
show configuration | no-more
```
Tested on vSRX | Junos: 19.2R1.8

[junos-ssh-access.txt](https://github.com/rconfig/rConfig-templates/files/3772858/junos-ssh-access.txt)

**Comment by rkayutkin** [comment]
@Maxonet 

I appreciate the reply.

Looks like I still get the same problem where the configuration is not copied. How are you adding the device? I might be missing something when I actually add the device to rconfig. I tried both of the templates by the way and still see the same thing.

**Comment by rkayutkin** [comment]
@Maxonet 

I looked further into it and your script is actually working to initiate the connection. I am having issues with syntax because for whatever reason rconfig thinks that "show startup-config" is juniper command.

**Comment by rkayutkin** [comment]
@Maxonet 

Appreciate all the help, looks like I was able to get it working.
