### ISSUE TITLE
config has been cut

### ISSUE THREAD

**Issue by oy1978** [rconfig/rConfig-templates#33]
Hi ,
I tried to back cisco and fortigate config , and have setup let them to show all config no paging.
but the config will cut(cannot backup all config) . 

does there have some setting need to fine tune?

Thanks.

**Comment by Virg1984** [comment]
Hi , Did you get a chance to resolve it.
i am getting same error on SG300 , only half config is showing

**Comment by rconfig** [comment]
Usually you device prompt is not correct in rConfig, or is not completed.. I.e. You use '#' instead of 'router1#'
