### ISSUE TITLE
Telnet not working

### ISSUE THREAD

**Issue by wajahatraza** [rconfig/rConfig-templates#4]
Hi,

I have deployed version 3.8.7 and I am saving the configuration of Cisco routers and switches. The issue i am facing is that rConfig is not showing the output when I am connecting via Telnet. It is working fine when I am using SSH to do same. I have checked the rConfig logs and it seems that there is no issue in communication with the device (see below), I have also verified that the device is sending traps when show running-config command is executed.

2018-03-12  16:07:42 CONN Success: Show Command 'show running-config' for device  'R1' successful (File: /lib/ajaxHandlers/ajaxDownloadNow.php)
--
2018-03-12 16:07:42  CONN Success: Connected to R1 (19.16.57.4) for Router ID 10  - in (File: /lib/ajaxHandlers/ajaxDownloadNow.php)

But, when the execution is completed, rConfig is returning blank fine in output. I have also check via command link and found that the output files are empty incase of using TELNET. Please also note that I am able to telnet the device using the OS (Centos 7) of rConfig.

Regards
Wajahat

**Comment by pauloj95** [comment]
I have the same problem ... any solution ?

Thanks

**Comment by ayad99** [comment]
Hi

We had the same issue. I have checked all the points suggested here (and in kb2001) by rConfig team. But it simply does not work with Telnet. Interestingly I used another tool and it picked up the config dump fine using the same Telnet credentials. So this is not a device config issue, or device credential issue. And this is not a rConfig issue as the settings are pretty straight forward. SSH works fine though in rConfig. It seems like there is a hidden bug in rConfig.

I understand that the rConfig tool is free, but the support is paid. But the way rConfig team is asking to buy support to identify this hidden issue appears bit unethical. It would have been better if rConfig was not offered as a free tool and rather had a paid subscription in the first place. At least we would all know what to expect.

**Comment by SmokyTheBear712** [comment]
Hi Guys, don't know if this was fixed for you, but I tested it, and send a email on the Bug email address (bugs@rconfig.com) the gent happily replied, fixed the problem and updated the software. Please try the latest version, and it will work. Good Luck !!

**Comment by rconfig** [comment]
issue should be resolved in new 3.9
