### ISSUE TITLE
rConfig | Command show running-config output stopping after a few lines. extreme network switch

### ISSUE THREAD

**Issue by dlyle91** [rconfig/rConfig-templates#43]
Hi all title says it all. i can get the device to connect and the command to run but it seems to only show output of like 10 lines and then stops. i did read through a bunch or other post so i have tried a few things to fix this the main things i did. was i added the whole device name in the main prompt. i ran the chown -R apache /home/rconfig command. and i tired multiple adjustment to the template to make it work. seems like the command to disable paging is not working (pagingCmd:). if i manually ssh to the switch and rung the disable paging command before i run the manual job then the show run command works just fine. so it seems like the paging part of the template is not taking effect. Any help would be appreciated this is my first time setting this up so i may have configured something wrong. thanks for all the help everyone gives.

i have put the template that i am using in this message as well in case someone sees something stupid i did. maybe a typing error im not seeing.
 this is for an extreme networks ers 4950gts

Edit:so im thinking my issue might be because once the device loges in you still need to hit enter once to get the prompt to type in. does anyone know how i can add a click enter after you login before it tries to type any commands?

# rConfig connection template - DO NOT EDIT DIRECTLY
## run 'chown -R apache /home/rconfig' on your rconfig server CLI
    ## all items below that contain free text should be contained within quotation marks " "
    ## For new community submitted templates visit: https://github.com/rconfig/rConfig-templates

main:
  name: "Extreme EXOS - SSH - No Enable"
  desc: "Extreme EXOS SSH based connection with enable mode"
connect:
  # connection timeout in seconds
  timeout: 60
  # type either telnet or ssh - must be in lowercase
  protocol: ssh
  # type port number for connection protocol choose from 1 - 65535
  port: 22
auth:
  # Set username name prompt. Must be in quotes. If left blank, username will not be sent.
  username: "username:"
  # Set password name prompt. Must be in quotes
  password: "password:"
  # Set enable mode on or off
  enable: off
  # set enable mode command. Must be in quotes
  enableCmd: " "
  # set enable mode password prompt. Must be in quotes
  enablePassPrmpt: "password:"
  # set HP 'press any key' status. Is 'on' or 'off'
  hpAnyKeyStatus: off
  # set HP 'press any key' prompt.
  hpAnyKeyPrmpt: "Press <SPACE> to continue or <Q> to quit:"
config:
    # Experimental: Some vendors use different linebreak settings. Choose 'n' (default) or 'r'
    linebreak: "n"
    # Disable config scrolling/ paging command. on/off
    paging: on
    # Disable config scrolling/ paging command. Leave blank, or set as required. Must place command in quotations
    pagingCmd: "terminal length 0"
    # re-enable config scrolling/ paging command. Leave blank, or set as required. Must place command in quotations
    resetPagingCmd: "terminal length 5"
    # Set pager prompt. Must place command in quotations
    pagerPrompt: "Next page: Space, quit: Q"
    # Set pager prompt key-stroke. Must place command in quotations
    pagerPromptCmd: " "
    # Save configuration command. Leave blank, or set as required. Must be in quotes
    saveConfig: " "
    # Set exit command. Must place command in quotations
    exitCmd: "quit"

**Comment by AlphaRedFox** [comment]
any update on this ? I'm having the same issue.
