### ISSUE TITLE
Mikrotik new RouterOS version SSH stopped working

### ISSUE THREAD

**Issue by alien8tive** [rconfig/rConfig-templates#45]
Hi

Since the Mikrotik v6.49, rconfig ssh download configuration stopped working.

When attempting a configuration download (even though SSH works), I get the following message:

`Failure: Unable to connect via SSH to HOST for command (/export verbose) when running Router ID 72
Command '/export verbose' ran successfully
Manual download completed`

Enabling debug in rconfig, it appears that the command does not wait for the banner to complete or the main prompt of ">". Here is an example of a working router on older OS

> <- NET_SSH2_MSG_CHANNEL_DATA (since last: 0.052, network: 0.0001s)
00000000  00:00:00:02:00:00:00:39:0d:1b:5b:39:39:39:39:42  .......9..[9999B
00000010  0d:1b:5b:39:39:39:39:42:0d:0d:0d:1b:5b:39:39:39  ..[9999B....[999
00000020  39:42:5b:61:64:65:70:74:40:63:70:65:30:2e:31:31  9B[XXXX@cpe0.11
00000030  39:34:31:20:28:50:72:69:6d:61:72:79:29:5d:20:3e  941 (Primary)] >
00000040  20

> -> NET_SSH2_MSG_CHANNEL_DATA (since last: 0.0001, network: 0s)
00000000  00:00:00:00:00:00:00:10:2f:65:78:70:6f:72:74:20  ......../export
00000010  76:65:72:62:6f:73:65:0d                          verbose.

> <- NET_SSH2_MSG_CHANNEL_DATA (since last: 0.0035, network: 0s)
00000000  00:00:00:02:00:00:00:11:2f:65:78:70:6f:72:74:20  ......../export
00000010  76:65:72:62:6f:73:65:0d:0a                       verbose..

and here is one on the newer OS

> <- NET_SSH2_MSG_CHANNEL_DATA (since last: 0.0132, network: 0.0001s)
00000000  00:00:00:02:00:00:00:2f:0d:1b:5b:39:39:39:39:42  ......./..[9999B
00000010  0d:1b:5b:39:39:39:39:42:0d:0d:0d:1b:5b:39:39:39  ..[9999B....[999
00000020  39:42:5b:61:64:65:70:74:40:63:70:65:30:2e:31:31  9B[XXXX@cpe0.11
00000030  35:31:37:5d:20:3e:20                             517] >

> -> NET_SSH2_MSG_CHANNEL_DATA (since last: 0.0001, network: 0s)
00000000  00:00:00:00:00:00:00:10:2f:65:78:70:6f:72:74:20  ......../export
00000010  76:65:72:62:6f:73:65:0d                          verbose.

> <- NET_SSH2_MSG_CHANNEL_DATA (since last: 0.0093, network: 0s)
00000000  00:00:00:02:00:00:01:00:2f:0d:5b:61:64:65:70:74  ......../.[XXX
00000010  40:63:70:65:30:2e:31:31:35:31:37:5d:20:3e:20:2f  @cpe0.11517] > /
00000020  1b:5b:4b:65:0d:5b:61:64:65:70:74:40:63:70:65:30  .[Ke.[XXX@cpe0
00000030  2e:31:31:35:31:37:5d:20:3e:20:2f:65:1b:5b:4b:78  .11517] > /e.[Kx
00000040  0d:5b:61:64:65:70:74:40:63:70:65:30:2e:31:31:35  .[XXX@cpe0.115
00000050  31:37:5d:20:3e:20:2f:65:78:1b:5b:4b:70:0d:5b:61  17] > /ex.[Kp.[
00000060  64:65:70:74:40:63:70:65:30:2e:31:31:35:31:37:5d  XXX@cpe0.11517]
00000070  20:3e:20:2f:65:78:70:1b:5b:4b:6f:0d:5b:61:64:65   > /exp.[Ko.[XXX
00000080  70:74:40:63:70:65:30:2e:31:31:35:31:37:5d:20:3e  @cpe0.11517] >
00000090  20:2f:65:78:70:6f:1b:5b:4b:72:0d:5b:61:64:65:70   /expo.[Kr.[XXX
000000a0  74:40:63:70:65:30:2e:31:31:35:31:37:5d:20:3e:20  @cpe0.11517] >
000000b0  2f:65:78:70:6f:72:1b:5b:4b:74:0d:5b:61:64:65:70  /expor.[Kt.[XXX
000000c0  74:40:63:70:65:30:2e:31:31:35:31:37:5d:20:3e:20  @cpe0.11517] >
000000d0  2f:65:78:70:6f:72:74:1b:5b:4b:20:0d:5b:61:64:65  /export.[K .[XXX
000000e0  70:74:40:63:70:65:30:2e:31:31:35:31:37:5d:20:3e  @cpe0.11517] >
000000f0  20:2f:65:78:70:6f:72:74:20:1b:5b:4b:76:0d:5b:61   /export .[Kv.[
00000100  64:65:70:74:40:63:70:65                          XXX@cpe

Any help will be much appreciated.

**Comment by nickhal** [comment]
Hi @alien8tive,

same error and problem. This label is displayed on the screen:
`Failure: Unable to connect via SSH to xxxx for command (export) when running Router ID 
Command 'export' ran successfully
Manual download completed`

Too bad the command actually failed and the generated backup file is empty.

Any suggestions of this?
Thank you

**Comment by alien8tive** [comment]
Nah, looking at this issue again. None of the upgraded Mikrotiks to version 6.49.2 are able to backup configuration or push code snippets, even though the SSH connection is working 100%

**Comment by alien8tive** [comment]
The anniversary is coming up for when I opened this :) 
No joy.
Gonna close it since we've moved to use Ansible to backup, then stash the version to AWS S3.
