### ISSUE TITLE
Switch Huawei

### ISSUE THREAD

**Issue by Fquetaud** [rconfig/rConfig-templates#49]
Hello,

I have a problem with Huawei switches. with display current-configuration, I don't get the complete configuration file.

do you have the solution?

Thank you

**Comment by rmacordeiro** [comment]
hi,

I have the exact same problem.

Configuration is not complete and it is not always on the same point.

**Comment by rmacordeiro** [comment]
I extended the timeout from the 5 sec I had to 60 sec and now it works just fine.
This was changed inside the template.

Let's see if, in the next coming days, all will be good.
