### ISSUE TITLE
Blank show run-config output Cisco WLC

### ISSUE THREAD

**Issue by rizkhat** [rconfig/rConfig-templates#6]
I am unable to connect to Cisco WLC 5508 (Product Version - 8.2.130.0) via ssh. So tried telnet, which worked. However, I am getting blank output of the commands (show cdp neigh & show run-config). I have also tried using "show run-config | b System" to avoid the intial "Press Enter to continue..." prompt but with no positive results.

**Comment by rconfig** [comment]
I have removed the WLC template at this time due to a defect, and will put it on the backlog when demand for it increases

**Comment by rickrb** [comment]
Hello guys, any news on this? We really need WLC backup here.

**Comment by stephenstack** [comment]
you will need to purchase support for custom connection templates.
