### ISSUE TITLE
Autoload.php - anyone?

### ISSUE THREAD

**Issue by AchillesD9** [rconfig/rConfig-templates#7]
Hi,

Has anyone experienced the following issue ? 

PHP Warning:  require(/home/rconfig/vendor/autoload.php): failed to open stream: No such file or directory in /home/rconfig/classes/connection2.class.php on line 17

Warning: require(/home/rconfig/vendor/autoload.php): failed to open stream: No such file or directory in /home/rconfig/classes/connection2.class.php on line 17
PHP Fatal error:  require(): Failed opening required '/home/rconfig/vendor/autoload.php' (include_path='.:/usr/share/pear:/usr/share/php') in /home/rconfig/classes/connection2.class.php on line 17

Fatal error: require(): Failed opening required '/home/rconfig/vendor/autoload.php' (include_path='.:/usr/share/pear:/usr/share/php') in /home/rconfig/classes/connection2.class.php on line 17

I'm currently seeing this when issuing a manual download on dell ? the script was working however it just stopped working.

Thanks

**Comment by rconfig** [comment]
you did not follow the upgrade instructions. See the instructions here...
You can manually copy the vendors directory out of the zip file and copy into /home/rconfig
https://www.rconfig.com/download-menu
