### ISSUE TITLE
Backups Fortigate 

### ISSUE THREAD

**Issue by panhala** [rconfig/rConfig-templates#9]
Hi,

I trying to find the way to backup fortigate, unfortunately i'm not success. Could you tell me how to backup fortigate?

**Comment by panhala** [comment]
Now i have problem with backup. it didn't backup full configuration.
only several line as you see below image:
![image](https://user-images.githubusercontent.com/11862935/44135080-b38108ce-a091-11e8-8e3f-d44993ec8965.png)

Can you tell me how to fix this problem?

**Comment by rConfigRich** [comment]
Hello Panhala, my name is Rich with rConfig. Can you please direct your question directly to our support email (help@rconfig.com). From there we can work to see if this is something we can assist you with sorting out. Thank you.

**Comment by amaurybsouza** [comment]
@rConfigRich do you know any template for Extreme Switches? If I create the template, can I add in the GitHub page?

Thanks.
